### ISSUE TITLE
Convert call data to multicall inputs

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#182] opened 2021-09-27 19:07 UTC
**Problem Description**
When displaying a multicall proposal, DXvote now shows the call data and the contract it's interacting with. On Alchemy, it shows you all of the inputs so that you can verify the proposal. F

or the buyback proposals, that would have the order info. On alchemy it's raw data (0x and lots of decimals) but it would be nice to have DXvote display that and token names/regular amounts, so that voters can verify. 

DXvote:

<img width="869" alt="Screen Shot 2021-09-27 at 3 01 38 PM" src="https://user-images.githubusercontent.com/47428627/134969513-8ce1809a-0708-4e97-a6c3-e8cb22d53e1c.png">

vs. Alchemy
<img width="677" alt="Screen Shot 2021-09-27 at 3 05 57 PM" src="https://user-images.githubusercontent.com/47428627/134969628-18d98d3f-b5ca-4cc0-b5fa-191947ef63a1.png">

**Comment by rossneilson** [comment] 2021-09-28 07:54
Pretty sure this is a duplicate of #7 
Since this is a more detailed issue description feel free to delete the older one or just close them at the same time

**Closed as completed** 2021-10-19 10:26 UTC
Labels: Enhancement, High Priority
