### ISSUE TITLE
UI needs to allow users to "6. redeemDaoBounty →"

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#375] opened 2021-11-15 04:08 UTC
**Description**

xDXdao now has xGEN
https://blockscout.com/xdai/mainnet/address/0xe716EC63C5673B3a4732D22909b38d779fa47c3F/tokens

Need to make the UI show the "6. redeemDaoBounty →" so people can REDEEM

**Comment by rossneilson** [comment] 2021-11-15 13:25
Duplicate of #366

**Closed as completed by rossneilson** 2021-11-15 13:25 UTC
Labels: Bug
